version: "3"

services:

  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"

  report-service:
    build: ./report-service
    ports:
      - "3001:3001"

  api-gateway:
    build: ./api-gateway
    ports:
      - "3002:3002"
